# Generated by Django 5.2.15 on 2026-07-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactleads',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
